@startuml Dependency_Root
' Image can be obtained from
' https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

' Write all modules here
object Animator {
    * animate()
}

object Utils #LightBlue {
    * Vector
    * Consts
}

' Write all dependencies here
' X --> Y means X depends on Y
Animator --> Utils

@enduml